### PR TITLE
Drawer menu items now supports Labels - DEMO

### PR DESCRIPTION
**Pull request by satvikmaker**
Drawer menu items now supports Labels - DEMO. In reference to the **[commit](https://github.com/react-native-material-design/react-native-material-design/pull/9) in the lib**.

**Screenshot-**

drawer labels

### CODE REVIEW

**Comment by Ehesp** [comment]
Cheers - once 0.3.0 is out I'll merge. Shouldn't be long.

**Comment by satvikmaker** [comment]
WOW! Awesome :+1: I am all geared up! :)

**Comment by satvikmaker** [comment]
Unless we merge this PR, I will not able to create a new PR or checkin for uploading the demo app. :(

**Comment by Ehesp** [comment]
I might just push up 0.3 as is without the List bit yet (not had chance to do it). Then I can merge in the dev branch of this which has the changes needed.

**Comment by satvikmaker** [comment]
Yeah! Ok. Carry forward List View task to 0.4 release :)

**Comment by satvikmaker** [comment]
Let me know when this PR can be merged. I have some commits waiting on my local.

**Comment by Ehesp** [comment]
Okay are they anything breaking? The dev branch on here has quite a lot of changes (fixes for 0.3 and some other handy things.

**Comment by satvikmaker** [comment]
Nope. The current PR works fine. And the other commits are not code related for now. They are mostly enhancing the README & Docs. Adding APK etc.,

**Comment by satvikmaker** [comment]
In parallel I am working on a Gridview component for material design. When it comes to a decent shape, you can verify it. And then, we can push it to this repo. :)

**Comment by Ehesp** [comment]
Okay I'll sort it out.... Release 0.3, merge over the dev branch of this repo... then you can bring your updates over (will need an APK rebuild though I guess!)

**Comment by satvikmaker** [comment]
Yes. Will pull the latest changes & rebuild the APK after you complete the merge :)

**Comment by Ehesp** [comment]
Okay pulled over :)

**Comment by satvikmaker** [comment]
**UPDATE:**

I pulled the latest released code. Applied my changes on it & tested it. Its working fine on phone. Will go ahead and merge if that's ok.

**Here is the screenshot from the latest build-**

merge final commit

**Pull request merged**
